
dataset_name: CLUSTER 

num_rw_steps: 6 
dim_pe: 16 
in_dim: 7 
out_dim: 6 

epochs: 100
scheduler: cosine 
warmup: 5 
batch_size: 32 
lr: 0.001 
weight_decay: 1e-5 

gconv_dim: 48 
tlayer_dim: 48 

gconv_ffn_dropout: 0 
tlayer_attn_dropout: 0.5 
tlayer_ffn_dropout: 0.1 
tlayer_ffn_hidden_times: 2 

gconv_type: gcn 
num_layers: 16 
num_heads: 8 
middle_layer_type: residual 
skip_connection: short 
norm: bn 

out_layer: 1 

save_state = True 
seeds: 666 
