
dataset_name: ogbg-code2 

max_seq_len: 5 
num_vocab: 5000 
max_input_len: 1000 
segment_pooling: sum 

epochs: 30 
scheduler: linear 
warmup: 5 
batch_size: 32
lr: 0.0002 
weight_decay: 1e-6 

gconv_dim: 256 
tlayer_dim: 256 
gconv_ffn_dropout: 0 
tlayer_attn_dropout: 0 
tlayer_ffn_dropout: 0.4 
tlayer_ffn_hidden_times: 4 

gconv_type: gcn 
num_layers: 4 
num_heads: 4 
middle_layer_type: mlp 
skip_connection: none 
readout: cls 
norm: ln 

out_layer: 1 

save_state = True 
seeds: 666 


