
dataset_name: ZINC 

num_rw_steps: 20 
dim_pe: 28 
out_dim: 1 
node_num_types: 28 
edge_num_types: 4 

epochs: 2000 
scheduler: linear 
warmup: 50 
batch_size: 32 
lr: 0.001 
weight_decay: 1e-5 

gconv_dim: 64 
tlayer_dim: 64 

gconv_ffn_dropout: 0 
tlayer_attn_dropout: 0.5 
tlayer_ffn_dropout: 0 
tlayer_ffn_hidden_times: 2 

gconv_type: gin 
num_layers: 10 
num_heads: 4 
middle_layer_type: residual 
skip_connection: short 
readout: add 
norm: bn 

out_layer: 3 
out_hidden_times: 8 

save_state = True 
seeds: 42 
